const resourceSpecifications = {
	book: [
		{
			name: "publication",
			label: "Publication",
			type: "text",
			required: true,
			placeholder: "Enter publication...",
		},
		{
			name: "isbn",
			label: "ISBN",
			type: "text",
			required: false,
			placeholder: "Enter ISBN...",
		},
		{
			name: "edition",
			label: "Edition",
			type: "text",
			required: false,
			placeholder: "Enter edition...",
		},
		{
			name: "year",
			label: "Publication Year",
			type: "number",
			required: false,
			placeholder: "YYYY",
		},
		{
			name: "condition",
			label: "Condition",
			type: "text",
			required: true,
			placeholder: "Excellent, New, or explain in upto 2 lines.",
		},
	],
	notes: [
		{
			name: "subject",
			label: "Subject",
			type: "text",
			required: true,
			placeholder: "Enter subject...",
		},
		{
			name: "level",
			label: "Academic Level",
			type: "select",
			required: true,
			options: ["High School", "Undergraduate", "Graduate", "PhD"],
		},
		{
			name: "language",
			label: "Language",
			type: "text",
			required: false,
			placeholder: "English",
		},
		{
			name: "condition",
			label: "Condition",
			type: "text",
			required: true,
			placeholder: "Excellent, New, or explain in upto 2 lines.",
		},
	],
	research_paper: [
		{
			name: "journal",
			label: "Journal/Conference",
			type: "text",
			required: true,
			placeholder: "Enter journal name...",
		},
		{
			name: "year",
			label: "Publication Year",
			type: "number",
			required: true,
			placeholder: "YYYY",
		},
		{
			name: "doi",
			label: "DOI",
			type: "text",
			required: false,
			placeholder: "Enter DOI...",
		},
		{
			name: "condition",
			label: "Condition",
			type: "text",
			required: true,
			placeholder: "Excellent, New, or explain in upto 2 lines.",
		},
	],
	thesis: [
		{
			name: "university",
			label: "University",
			type: "text",
			required: true,
			placeholder: "Enter university...",
		},
		{
			name: "degree",
			label: "Degree Type",
			type: "select",
			required: true,
			options: ["Masters", "PhD", "Doctorate"],
		},
		{
			name: "year",
			label: "Completion Year",
			type: "number",
			required: true,
			placeholder: "YYYY",
		},
		{
			name: "condition",
			label: "Condition",
			type: "text",
			required: true,
			placeholder: "Excellent, New, or explain in upto 2 lines.",
		},
	],
	journal: [
		{
			name: "volume",
			label: "Volume",
			type: "text",
			required: false,
			placeholder: "Enter volume...",
		},
		{
			name: "issue",
			label: "Issue",
			type: "text",
			required: false,
			placeholder: "Enter issue...",
		},
		{
			name: "year",
			label: "Publication Year",
			type: "number",
			required: true,
			placeholder: "YYYY",
		},
		{
			name: "condition",
			label: "Condition",
			type: "text",
			required: true,
			placeholder: "Excellent, New, or explain in upto 2 lines.",
		},
	],

	other: [
		{
			name: "category",
			label: "Category",
			type: "text",
			required: false,
			placeholder: "Enter category...",
		},
		{
			name: "condition",
			label: "Condition",
			type: "text",
			required: true,
			placeholder: "Excellent, New, or explain in upto 2 lines.",
		},
	],
};
export default resourceSpecifications;
